/* eslint-disable quotes, quote-props, max-len */

// quoine

export default {
  "sign-in": {
    "title": "Sign In",
    "action": "Sign In",
    "email": "Email Address",
    "password": "Password",
    "code": "Authentication Code",
    "code-description": "An authentication code is required to sign in. This code has been sent via Authy or SMS to your mobile phone.",
    "back": "Back",
    "new-text": "Don't have an account?",
    "new-or": "or",
    // message
    "message-account-confirmed": "Your account has been confirmed. You can now sign in.",
    "message-password-updated": "Your password has been updated. You can now sign in with the new password.",
    "message-signed-out": "You have been signed out.",
    "message-need-sign-in": "Please sign in first.",
  },
  "sign-in-error": {
    "you-have-to-confirm-your-account-before-continuing": "Please confirm your account before continuing.",
    "your-password-is-incorrect": "Your password is incorrect.",
    "token-is-invalid": "This code is invalid.",
    "invalid-email-or-password": "Email address or password is invalid.",
    "verification-failed": "Authentication code is not valid.",
    "you-are-logging-in-from-a-new-ip-address-that-is-not-confirmed-yet-a-confirmation-link-has-been-sent-to-your-email-address-please-check-and-confirm-to-continue": "You are logging in from a new IP address that is not confirmed yet. A confirmation link has been sent to your email address. Please check and confirm to continue.",
  },
  "forgot-password": {
    "action-resend": "Resend password reset link",
    "action-send": "Send password reset link",
    "description": "Please enter your email address to receive password reset link.",
    "title": "Forgot Password?",
    "message-sent": "Password reset link has been sent. Please check your Inbox and/or Spam box for the link to proceed. If you don't see our email after 10 minutes, please click Resend.",
    "email": "Email Address",
  },
  "forgot-password-error": {
    "email-not-found": "Email address not found.",
    "email-can-t-be-blank": "Email address is required.",
  },
  "reset-password": {
    "new-password": "New Password",
    "new-password-help": "Password must have at least 8 characters and contain at least 1 lowercase letter, 1 uppercase letter, and 1 number.",
    "token": "Reset Token",
    "token-help": "Please enter the reset token that was sent to your email address.",
    "action": "Update Password",
    "title": "Reset Password",
  },
  "reset-password-error": {
    "reset-password-token-can-t-be-blank": "Token is required. Please enter the reset token that was sent to your email address.",
    "reset-password-token-is-invalid": "Token is invalid. Please enter the reset token that was sent to your email address.",
    "reset-password-token-expired": "Reset Password attempt has expired. Please return to Home Page and try again.",
    "password-is-too-short-minimum-is-8-characters": "Password must have at least 8 characters and contain at least 1 lowercase letter, 1 uppercase letter, and 1 number.",
  },
  "change-password": {
    "title": "Change Password",
    "action-submit": "Change",
    "action-cancel": "Cancel",
    "action-done": "Done",
    "input-next": "New",
    "input-current": "Current",
    "success": "Your password has been successfully updated.",
  },
  "change-password-error": {
    "password-update-failed": "Password update has failed.",
    "your-password-is-incorrect": "Your password is incorrect.",
  },
  "sign-up": {
    "title": "Sign Up",
    "action-next": "Next",
    "action-done": "Done",
    "action-sign-in": "Go to Sign in",
    "back": "Back",
    // ===
    "message-success": "Thank you for registering. The process is almost done! Further instructions have been sent to your email address.",
    // ===
    "step-1": "1. Account Type",
    "step-2": "2. Account Overview",
    "step-3": "3. Account Detail",
    "step-4": "4. Terms & Conditions",
    // ===
    "type-corporate-title": "Corporate",
    "type-corporate-description": "Registered account will serve a company.",
    "type-individual-title": "Personal",
    "type-individual-description": "Registered account will serve an individual.",
    // ===
    "email": "Email",
    "email-help": "This email will be used to sign in to your account.",
    "password": "Password",
    "password-help": "Password must have at least 8 characters and contain at least 1 lowercase letter, 1 uppercase letter, and 1 number.",
    "country": "Country of Residence",
    "country-sure": "I confirm that I will be staying in Japan.",
    "country-sure-help": "If there is any change, within 3 months from date of change you will need to provide notification regarding the change.",
    "us": "US tax liability",
    "us-no": "No",
    "us-yes": "Yes",
    "us-help": "If you are a \"US citizen\" or \"resident of the United States (those with permanent residency in the US, those with a stay of more than 183 days in the US\"), please select \"yes\".",
    "referral": "Promotion Code (optional)",
    "term-quoine": "I agree with <a href=\"https://www.quoine.com/terms\" target=\"_blank\">Terms &amp Conditions</a>.",
    "term-traders": "I agree with <a href=\"https://www.min-btc.com/document/terms.pdf\" target=\"_blank\">Terms &amp Conditions</a>.",
    "term-qryptos": "I agree with <a href=\"https://s3-ap-northeast-1.amazonaws.com/jfsa-qryptos/Terms+and+Conditions+QUOINE+PTE+LTD_V1.0.pdf\" target=\"_blank\">Terms &amp Conditions</a>.",
  },
  "sign-up-pi": {
    "name": "Name",
    "nationality": "Nationality",
    "address": "Address",
    "birth": "Date of Birth",
    "income": "Primary Source Of Income",
    "income-employed": "Employed",
    "income-other": "Other",
    "income-retired": "Retired",
    "income-self-employed": "Self-Employed",
    "income-job": "Job Title",
    "income-business-name": "Business Name",
    "income-business-type": "Business Type",
    "income-detail": "Source Of Income Detail",
  },
  "sign-up-pc": {
    "name": "Business Name",
    "type": "Business Type",
    "address": "Address",
    "website": "Website",
    "tax-id": "TAX",
    "vat-id": "VAT",
  },
  "sign-up-error": {
    "email-has-already-been-taken": "This email address has been taken.",
    "all-is-required": "All fields are required.",
    "terms": "Please go through Terms & Conditions thoroughly and accept them before proceeding.",
    "password-is-too-short-minimum-is-8-characters": "Password must have at least 8 characters and contain at least 1 lowercase letter, 1 uppercase letter, and 1 number.",
  },
  "demo": {
    "title": "Use a demo account",
    "email": "Demo account email",
    "action": "Enter demo mode",
    // ===
    "continue-title": "Continue Your Demo",
    "continue-overview": "Use your previous demo account to continue your trading progress.",
    "continue-description": "Please enter the email address of the demo account you want to resume.",
    "continue-found": "Below is the address of your last demo session on this browser.",
    // ===
    "new-title": "Start a New Demo",
    "new-overview": "Create a new demo account to try our app and its features to your heart's content!",
    "new-description": "The email address below will be used to create a demo account for you. This demo account can be accessed on all supported systems and browsers, as long as you use this address to resume.",
  },
  "sign-out": {
    "action": "Sign Out",
    "description": "Click SIGN OUT to end your session in this tab. You will also be signed out automatically when you close the tab.<br /><br />To end your session on all devices and browsers, check the box below.",
    "all": "End All Sessions",
    "title": "Sign Out",
  },
  "settings": {
    "title": "Settings",
    "back-to-trading": "Back to Trading",
    // ===
    "application-title": "Application",
    "theme-title": "Theme",
    // ===
    "profile-title": "Profile",
    // ===
    "security-title": "Security",
    "password-title": "Password",
    "sign-in-title": "Sign In",
    // ===
    "api-title": "API",
  },
  "daily-report": {
    "title": "Report",
    "label": "Receive Daily Reports",
  },
  "user": {
    "verification": "Verification",
    // ===
    "status": "Status",
    "status-documents-submitted": "Documents Submitted",
    "status-approved": "Approved",
    "status-declined": "Declined",
    "status-pending": "Pending",
    // ===
    "help-documents-submitted": "Your documents have been uploaded. Our staff will be reviewing and approving your account shortly. Note that account verification process will take 1-2 working days to complete.",
    "help-approved": "Your account has been approved. No further action is required.",
    "help-declined": "Your account verification request has been declined. Please note the following instructions and update your documents: {{ reason }}.",
    "help-pending": "Your account is not verified yet. Please upload the following documents for account verification:",
    "help-pending-jp": "Your account is not verified yet. Please upload the following documents for account verification:",
    "help-pending-jp-link": "Documents Explanation",
    "help-edit-info": "Please contact us at support@quoine.com if you would like to change any of your client information.",
    // ===
    "document-id": "ID Document",
    "document-id-help": "",
    "document-address": "Proof of Address",
    "document-address-help": "",
    "document-bank": "Bank Statement",
    "document-bank-help": "",
    "document-action": "Submit Documents",
    // ===
    "id": "User ID",
    "first-name": "First Name",
    "last-name": "Last Name",
    "email": "Email",
    "since": "Joined Since",
    "affiliate-code": "Affiliate code",
  },
  "user-error": {
    "invalid-types": "Please check your file types. Allowed types are: pdf, xps, jpg, jpeg, png, and gif.",
  },
  "edit-user": {
    "title": "Update user profile",
    "action": "Update user profile",
    "action-submit": "Submit",
    "action-cancel": "Cancel",
    "description": "Please contact us at support@quoine.com if you fall into one of the cases below:<br/>1. People residing outside of Japan (including  Japanese citizens)<br/>2. Family member of foreigner Politically Exposed Persons (PEPs)<br/>3. United States of America taxpayer",
    "message-no-changes": "Your information has not been changed.",
  },
  "tfa-manage": {
    "phone": "Phone",
    "title": "Two-Factor Authentication",
    "status-enabled": "Enabled",
    "status-not-enabled": "Not Enabled Yet",
    // ===
    "help-change-phone": "To change your phone numer, please contact our Support at support@quoine.com.",
    // ===
    "add-phone-title": "Add Phone Number",
    "add-phone-action": "Add",
    "add-phone-label": "Phone Number",
    "add-phone-description": "Please enter the new phone number.",
    // ===
    "toggle-title-enable": "Enable",
    "toggle-title-disable": "Disable",
    "toggle-action-enable": "Enable",
    "toggle-action-disable": "Disable",
    "toggle-description": "Please enter the code that was sent to your phone.",
    "toggle-label": "Authentication Code",
    // ===
    "action-cancel": "Cancel",
    "action-done": "Done",
  },
  "tfa-manage-error": {
    "en-authy-token-is-blank": "Authentication code is required.",
    "token-is-invalid": "Token is invalid.",
  },
  "token": {
    "id": "ID",
    "value": "Token/Secret",
    "value-copy": "Copy",
    "permissions": "Permissions",
    "none": "None",
    "value-message": "This Token/Secret is displayed one time only.",
    // ===
    "remove-title": "Delete Token",
    "remove-action": "Delete",
    "remove-description": "Are you sure want to delete this token? All devices and apps using this token will be unauthorized immediately.",
    // ===
    "add-title": "Create New API Token",
    "add-description": "Please select permissions for the new token:",
    "add-action-submit": "Create Token",
    "add-action-cancel": "Cancel",
    // ===
    "action-r": "Read",
    "action-w": "Write",
    // ===
    "name-accounts": "Accounts",
    "name-executions": "Executions",
    "name-orders": "Orders",
    "name-trades": "Positions",
    "name-trading-accounts": "Trading Accounts",
  },
};
