/* eslint-disable quotes, quote-props, max-len */

// quoine

export default {
  "sign-in": {
    "title": "ログイン",
    "action": "ログイン",
    "email": "メールアドレス",
    "password": "パスワード",
    "code": "コード",
    "code-description": "2段階認証が有効になっています。",
    "back": "戻る",
    "new-text": "新規口座申込はこちら",
    "new-or": "または",
    // ===
    "change-password-title": "パスワード変更は必要です",
    "change-password-message": "現在、仮パスワードでログインされています。安全のためパスワード変更をお願い致します。",
    "change-password-button": "パスワード変更",
    // message
    "message-account-confirmed": "アカウント承認に成功しました。",
    "message-password-updated": "パスワード再設定に成功しました。新しいパスワードでログインしてください。",
    "message-signed-out": "ログアウトしました。",
    "message-need-sign-in": "ログインしてください。",
  },
  "sign-in-error": {
    "you-have-to-confirm-your-account-before-continuing": "登録いただいたメールアドレスに確認メールを送信いたしました。メールをご確認ください。",
    "your-password-is-incorrect": "パスワードが正しくありません。",
    "token-is-invalid": "無効な認証コードです。",
    "invalid-email-or-password": "メールアドレスまたはパスワードをもう一度確認してください。",
    "verification-failed": "無効な認証コードです。",
    "you-are-logging-in-from-a-new-ip-address-that-is-not-confirmed-yet-a-confirmation-link-has-been-sent-to-your-email-address-please-check-and-confirm-to-continue": "未登録のIPアドレスからのログインを確認しました。登録のメールアドレスに送信されたメールにある、確認用リンクをご確認ください。",
    "country-restricted": "QRYPTOS is currently not available for this country.",
    "failed-attempt-limit-reached": "ログインを複数回失敗されたため、アカウントが一時的にロックされました。登録のメールアドレスにアカウントロック解除のためのメールを送信しましたのでご確認ください",
    "en-authy-your-account-is-suspended": "あなたのAuthyアカウントは停止されています。",
  },
  "forgot-password": {
    "help": "パスワードをリセットされる際は、<a href=\"mailto:support@quoine.com\">support@quoine.com</a>までご連絡ください。",
  },
  "change-password": {
    "title": "パスワード変更",
    "action-submit": "更新",
    "action-cancel": "キャンセル",
    "action-done": "確認",
    "input-next": "新しいパスワード",
    "input-current": "現在のパスワード",
    "success": "パスワード変更に成功しました。",
    "password-help": "8文字以上かつ、大文字・小文字・数字のすべてを含む必要があります。",
  },
  "change-password-error": {
    "password-update-failed": "パスワード更新に失敗しました。",
    "your-password-is-incorrect": "パスワードが間違っています",
  },
  "sign-up": {
    "title": "新規登録",
    "action-next": "次",
    "action-done": "新規登録",
    "action-sign-in": "ログインページへ進む",
    "back": "戻る",
    // ===
    "message-success": "ご登録頂きまして、誠にありがとうございます。あと少しで完了です。詳しい説明を記載したメールを送信いたしましたので、ご確認ください。",
    // ===
    "step-1": "１. 口座の種類",
    "step-2": "２. 口座[アカウント]状況",
    "step-3": "３. アカウントの詳細",
    "step-4": "４. 確認",
    // ===
    "type-corporate-title": "法人",
    "type-corporate-description": "法人口座をお申込みの方はこちら",
    "type-individual-title": "個人",
    "type-individual-description": "個人口座をお申込みの方はこちら",
    // ===
    "email": "メールアドレス",
    "email-help": "メールアドレスはアカウントにサインインするために使用されます。",
    "password": "パスワード",
    "password-help": "8文字以上かつ、大文字・小文字・数字のすべてを含む必要があります。",
    "country": "居住地国",
    "country-sure": "私は、日本以外に居住地国が無いことを確約します。",
    "country-sure-help": "日本以外に居住地国をお持ちのお客様は個人口座の開設はできません。また、居住地国に変更があった場合は、変更があった日から3ヶ月を経過する日までに異動届出書により申告する必要となります。",
    "us": "US税金負債",
    "us-no": "いいえ",
    "us-yes": "はい",
    "us-help": "\"米国籍\" または \"米国居住者（米国永住権をお持ちの方、米国での滞在日数が183日以上の方）\"に該当するお客様は\"はい\"をご選択ください。",
    "referral": "プロモコード（任意）",
    "term-quoine": "下記の<a href=\"https://www.quoine.com/terms\" target=\"_blank\">利用規約</a>に同意します。",
    "term-traders": "下記の<a href=\"https://www.min-btc.com/document/terms.pdf\" target=\"_blank\">利用規約</a>に同意します。",
    "term-qryptos": "I agree with <a href=\"https://s3-ap-northeast-1.amazonaws.com/jfsa-qryptos/Terms+and+Conditions+QUOINE+PTE+LTD_V1.0.pdf\" target=\"_blank\">Terms &amp Conditions</a>.",
  },
  "sign-up-pi": {
    "name": "名前",
    "nationality": "国籍",
    "address": "住所",
    "birth": "生年月日",
    "income": "収入源",
    "income-employed": "会社員",
    "income-retired": "退職",
    "income-other": "その他",
    "income-self-employed": "自営業",
    "income-job": "役職",
    "income-business-name": "会社名",
    "income-business-type": "業務形態",
    "income-detail": "収入詳細",
  },
  "sign-up-pc": {
    "name": "会社名",
    "type": "業務形態",
    "address": "アドレス",
    "website": "会社ウェブサイト",
    "tax-id": "Tax",
    "vat-id": "VAT",
  },
  "sign-up-error": {
    "email-has-already-been-taken": "既に登録済みのメールアドレスです。",
    "all-is-required": "全てのフィールドに入力する必要があります。",
    "terms": "利用規約に同意する必要があります。",
    "password-is-too-short-minimum-is-8-characters": "パスワードは最低8文字で、かつ1文字以上の大文字、小文字、数字を含む必要があります。",
    "country-restricted": "QRYPTOS is currently not available for this country.",
  },
  "demo": {
    "title": "デモアカウントを利用する",
    "email": "デモアカウントのメールアドレス",
    "action": "デモアカウントで進む",
    // ===
    "continue-title": "デモアカウントで続ける",
    "continue-overview": "以前使用されたデモアカウントで進むとデモ取引を続けられます。",
    "continue-description": "ご利用のデモアカウントのメールアドレスを入力ください。",
    "continue-found": "下記は以前使用したデモアカウントのメールアドレスです。",
    // ===
    "new-title": "新規デモアカウントで進む",
    "new-overview": "デモアカウントでトレード機能を無料体験できます。",
    "new-description": "下記のメールアドレスで新規デモアカウントを作成します。本デモアカウントを利用し続ける場合、このメールアドレスをメモしてください。",
  },
  "sign-out": {
    "action": "ログアウト",
    "description": "このブラウザからログアウトするにはログアウトボタンをクリックしてください。",
    "all": "全てのデバイス、ブラウザからログアウトする。",
    "title": "ログアウトしますか？",
  },
  "settings": {
    "title": "設定",
    "back-to-trading": "ダッシュボードに戻る",
    // ===
    "application-title": "お客様情報",
    "theme-title": "テーマ",
    // ===
    "profile-title": "プロフィール",
    // ===
    "security-title": "セキュリティ",
    "password-title": "パスワード",
    "tfa-title": "二段階認証",

    "api-access-title": "APIアクセス",
    "api-title": "トークン",
    "ip-title": "IPホワイトリスト",
  },
  "daily-report": {
    "title": "取引レポート",
    "label": "取引レポートを受信する。",
  },
  "user": {
    "verification": "口座開設状況",
    // ===
    "status": "ステータス",
    "status-documents-submitted": "書類審査中",
    "status-approved": "開設済",
    "status-declined": "書類不備",
    "status-pending": "書類提出前",
    "status-banned": "アカウント停止",
    // ===
    "help-documents-submitted": "本人確認書類をご送付いただきありがとうございます。弊社スタッフにより審査を進めさせていただきます。",
    "help-approved": "入出金及びお取引が可能です。",
    "help-declined": "アカウント認証に失敗しました。下記の書類の再送付をお願いいたします。",
    "help-pending": "お取引いただくには下記書類を送付が必要となります。",
    "help-pending-jp": "お取引いただくには本人確認書類をアップロードしてください。",
    "help-pending-jp-link": "本人確認書類",
    "help-banned": "アカウント停止を解除する場合は support@quoine.com までご連絡ください。",
    "help-edit-info": "登録情報を変更する場合は、support@quoine.comまでご連絡ください。",
    // ===
    "document-id": "本人確認書類（顔写真付）",
    "document-id-help": "運転免許書、パスポートなど",
    "document-address": "住所証明書",
    "document-address-help": "住民票、公共料金領収書など（本人確認書類とは別の書類が必要です。）",
    "document-bank": "銀行口座照会の明細",
    "document-bank-help": "通帳の見開き、口座取引明細、口座照会明細、ネットバンクのスクリーンショットなど口座名・口座番号・支店情報がわかるもの",
    "document-action": "本人確認書類をアップロードする",
    // ===
    "id": "ユーザーID",
    "first-name": "名",
    "last-name": "姓",
    "email": "メールアドレス",
    "since": "申込日",
    "affiliate-code": "アフィリエイトコード",
  },
  "user-error": {
    "invalid-types": "無効なファイルタイプです。PDF／XPS／JPG／JPEG／PNG／GIFのファイルをアップロードしてください。",
  },
  "edit-user": {
    "title": "口座情報変更",
    "action": "口座情報変更",
    "action-submit": "変更",
    "action-cancel": "取り消し",
    "description": "以下の場合は、support@quoine.comまでご連絡ください。<br />１）転勤等で海外居住となる場合<br />２）外国PEPsに該当することとなった場合<br />３）米国納税義務が発生することとなった場合",
    "message-no-changes": "登録情報が変更されていません。",
  },
  "tfa-manage": {
    "status": "2要素認証ステータス",
    "status-enabled": "認証済み",
    "status-not-enabled": "未設定",
    // ===
    "disable-description": "2要素認証の設定自体を無効化したい場合は、<a href=\"mailto:support@quoine.com\">support@quoine.com</a>までご連絡ください。",
    "authy-warning": "Authyは今後ご使用になれません。Google認証アプリの設定を行うには、まずAuthyでの2要素認証の設定を一度無効化する必要があります その後、Google認証アプリを用いて、2要素認証を再設定ください。",
    // ===
    "app": "2要素認証アプリ",
    "app-authy": "Authy",
    "app-ga": "Google Authenticator",
    // ===
    "action-enable": "有効化",
    "action-disable": "無効化",
    "action-cancel": "キャンセル",
    // ===
    "form-input": "トークン",
    "form-authy-description": "トークンをご入力ください。",
    "form-ga-description": "確認コードの所得のため、Google認証システムを起動してください。",
  },
  "tfa-manage-error": {
    "en-authy-verification-failed": "無効なトークンです。",
    "verification-failed": "無効なトークンです。",
    "en-authy-token-is-blank": "トークンの入力が必要です。",
    "token-is-invalid": "無効なトークンです。",
  },
  "tfa-phone": {
    "phone": "携帯番号",
    "help-change-phone": "電話番号を更新するには、support@quoine.comへご連絡ください。",
    // ===
    "add-phone-title": "携帯番号を設定する",
    "add-phone-action": "設定",
    "add-phone-label": "携帯番号",
    "add-phone-description": "新しい携帯番号をご入力ください。",
  },
  "tfa-ga": {
    "scan-barcode": "このQRコードをGoogle Authenticatorでスキャンしてください。",
    "enter-code": "アプリに表示される6つの数字を入力してください。",
    "enter-code-description": "QRコードをスキャンすると、アプリに下記の欄に入力するための6つの数字が表示されます。",
    "enter-key-description": "QRコードでの読み込みではなく、キーの入力によっても2要素認証を設定できます。",
  },
  "token": {
    "id": "トークンID",
    "value": "トークンシークレット",
    "value-copy": "コピー",
    "permissions": "許可",
    "none": "なし",
    "value-message": "このトークンシークレットは一度しか表示されません。",
    // ===
    "remove-title": "トークンを削除する",
    "remove-action": "削除する",
    "remove-action-yes": "削除する",
    "remove-action-no": "キャンセル",
    "remove-description": "ただいまトークンを利用している全てのデバイスまたはアプリをすぐに無許可します。トークンを削除しますか。",
    // ===
    "add-title": "APIトークンを新規作成する",
    "add-description": "APIトークンの許可をご選択ください。",
    "add-action-submit": "確認",
    "add-action-cancel": "キャンセル",
    // ===
    "action-r": "Read",
    "action-w": "Write",
    // ===
    "name-accounts": "アカウント",
    "name-executions": "実行",
    "name-orders": "注文",
    "name-trades": "ポジション",
    "name-trading-accounts": "取引口座",
  },
  "ip": {
    "add-title": "新しいIPを追加",
    "add-main-description1": "ホワイトリストが空のデフォルト状態の場合は、IPでの制限はありません。",
    "add-main-description2": "新しくIPをホワイトリストに追加すると、そのIPからのリクエストだけが許可されます。 これはすべての既存のAPIキーに適用されるので、何かを追加するときにはすべてのサーバーIPをホワイトリストに含めるようにしてください。",
    "add-description": "登録のIPアドレスと認証コードを以下に入力ください。",
    "add-action-submit": "追加",
    "add-action-cancel": "キャンセル",
    // ===
    "input-ip": "IPアドレス:",
    "input-code": "認証コード:",
    "id": "ID",
    "ip": "IP",
    "status": "ステータス",
    "remove-button": "IPを削除",
    "dismiss-button": "閉じる",
    "remove-action-yes": "削除",
    "remove-action-no": "キャンセル",
    "status-awaiting-confirmation": "未確認",
    "status-confirmed": "確認済",
    "remove-description": "このIPアドレスを削除すると、現在システムとの接続に使用されている全てのAPIキーでのアクセスが不可になります。",
    "checkmail-notification": "IPアドレスの確認のため、メールをご確認ください。",
  },
  "ip-error": {
    "verification-failed": "無効な認証コードです。",
    "token-is-invalid": "無効な認証コードです。",
    "ip-has-been-existed": "このIPアドレスはすでに登録済みです。",
    "ip-existing-ip": "このIPアドレスはすでに登録済みです。",
    "ip-wrong-format": "無効なIPアドレスです。",
    "cannot-remove-all-ips": "最新のIPアドレスは削除できません。",
  },
};
