/* eslint-disable quotes, quote-props, max-len */

// quoine

export default {
  "sign-in": {
    "title": "登录",
    "action": "登录",
    "email": "邮箱地址",
    "password": "密码",
    "code": "验证码",
    "code-description": "需要验证码才能登录，该验证码已通过 Authy 或短信发送至您的手机",
    "back": "返回",
    "new-text": "没有账户",
    "new-or": "或者",
    // message
    "message-account-confirmed": "账户已确认，您现在可以登录",
    "message-password-updated": "密码已更新，请使用新密码登录",
    "message-signed-out": "已登出",
    "message-need-sign-in": "请先登录",
  },
  "sign-in-error": {
    "you-have-to-confirm-your-account-before-continuing": "请先确认您的账户",
    "your-password-is-incorrect": "密码不正确",
    "token-is-invalid": "验证码无效",
    "invalid-email-or-password": "邮箱地址或密码无效",
    "verification-failed": "验证码无效",
    "you-are-logging-in-from-a-new-ip-address-that-is-not-confirmed-yet-a-confirmation-link-has-been-sent-to-your-email-address-please-check-and-confirm-to-continue": "本次登陆的IP地址尚未被验证，验证链接已经发送到您的邮箱，请查收",
    "country-restricted": "对不起，QRYPTOS在当前国家暂时没有提供服务，请耐心等待。",
  },
  "forgot-password": {
    "help": "如需要重置您的密码，请联系<a href=\"mailto:support@quoine.com\">support@quoine.com</a>",
  },
  "change-password": {
    "title": "更改密码",
    "action-submit": "更改",
    "action-cancel": "取消",
    "action-done": "完成",
    "input-next": "新密码",
    "input-current": "原密码",
    "success": "密码已成功更新",
    "password-help": "密码必须至少包含 8 个字符并且包含至少 1 个小写字母、1 个大写字母和 1 个数字",
  },
  "change-password-error": {
    "password-update-failed": "密码更新失败",
    "your-password-is-incorrect": "您的密码不正确",
  },
  "sign-up": {
    "title": "注册",
    "action-next": "下一项",
    "action-done": "完成",
    "action-sign-in": "转至登录页",
    "back": "返回",
    // ===
    "message-success": "感谢您的注册，验证链接将发送至您的邮箱",
    // ===
    "step-1": "1. 账户类型",
    "step-2": "2. 账户概览",
    "step-3": "3. 账户详情",
    "step-4": "4. 条款声明",
    // ===
    "type-corporate-title": "公司",
    "type-corporate-description": "注册账户将用于公司",
    "type-individual-title": "个人",
    "type-individual-description": "注册账户将用于个人",
    // ===
    "email": "电子邮件",
    "email-help": "此电子邮件将用于登录您的账户",
    "password": "密码",
    "password-help": "密码必须至少包含 8 个字符并且包含至少 1 个小写字母、1 个大写字母和 1 个数字",
    "country": "居住国",
    "country-sure": "确认居住国",
    "country-sure-help": "如有变更，请在变更日起 3 个月内联系我们",
    "us": "美国纳税义务",
    "us-no": "否",
    "us-yes": "是",
    "us-help": "如果您是\"美国公民\"或\"美国居民（在美国有永久居留权的人，在美国居住超过 183 天的人\"），请选择\"是\"",
    "referral": "促销码（选填）",
    "term-quoine": "我同意<a href=\"https://www.quoine.com/terms\" target=\"_blank\">条款声明</a>",
    "term-traders": "我同意<a href=\"https://min-btc.com/terms\" target=\"_blank\">条款声明</a>",
    "term-qryptos": "我同意<a href=\"https://s3-ap-northeast-1.amazonaws.com/jfsa-qryptos/Terms+and+Conditions+QUOINE+PTE+LTD_V1.0.pdf\" target=\"_blank\">条款声明</a>",
  },
  "sign-up-pi": {
    "name": "姓名",
    "nationality": "国籍",
    "address": "地址",
    "birth": "生日",
    "income": "主要收入来源",
    "income-employed": "就业",
    "income-other": "其他",
    "income-retired": "退休",
    "income-self-employed": "个体营业",
    "income-job": "职位",
    "income-business-name": "企业名称",
    "income-business-type": "企业类型",
    "income-detail": "详述收入来源",
  },
  "sign-up-pc": {
    "name": "企业名称",
    "type": "企业类型",
    "address": "地址",
    "website": "网站",
    "tax-id": "TAX",
    "vat-id": "VAT",
  },
  "sign-up-error": {
    "email-has-already-been-taken": "此电子邮件已被占用",
    "all-is-required": "所有字段都为必填项",
    "terms": "请仔细阅读条款声明，然后继续",
    "password-is-too-short-minimum-is-8-characters": "密码必须至少包含 8 个字符并且包含至少 1 个小写字母、1 个大写字母和 1 个数字",
    "country-restricted": "对不起，QRYPTOS在当前国家暂时没有提供服务，请耐心等待。",
  },
  "demo": {
    "title": "模拟账户",
    "email": "电子邮件",
    "action": "进入模拟模式",
    // ===
    "continue-title": "继续您的模拟模式",
    "continue-overview": "使用之前的模拟账户继续您的交易",
    "continue-description": "请输入希望恢复的模拟账户的邮箱地址",
    "continue-found": "下方是您在此浏览器上最后一次模拟会话所用的地址",
    // ===
    "new-title": "开始新的模拟",
    "new-overview": "创建一个新的模拟账户并试用应用及其功能",
    "new-description": "下方邮箱地址将用于为您创建一个模拟账户，您可通过所支持的系统和浏览器访问此模拟账户",
  },
  "sign-out": {
    "action": "登出",
    "description": "点击登出交易系统。当关闭标签页时也将自动登出。<br /><br />如要结束所有设备和浏览器中登录，请勾选下方选框",
    "all": "登出所有",
    "title": "您要登出吗？",
  },
  "settings": {
    "title": "设置",
    "back-to-trading": "返回交易",
    // ===
    "application-title": "申请",
    "theme-title": "主题",
    // ===
    "profile-title": "个人资料",
    // ===
    "security-title": "安全",
    "password-title": "密码",
    "tfa-title": "双重验证",
    // ===
    "api-title": "API接口",
  },
  "daily-report": {
    "title": "日报",
    "label": "接收日报",
  },
  "user": {
    "verification": "审查",
    // ===
    "status": "状态",
    "status-documents-submitted": "文件已提交",
    "status-approved": "已核准",
    "status-declined": "已拒绝",
    "status-pending": "待定",
    "status-banned": "被禁止",
    // ===
    "help-documents-submitted": "您的文件已上传，我们的员工将尽快审查并核准您的账户。账户核查过程需要 1-2 个工作日",
    "help-approved": "您的账户已被核准，无需进一步操作",
    "help-declined": "您的账户核准请求已被拒绝。请更新您的文件：{{ reason }}。",
    "help-pending": "您的账户尚未得到核准。请上传以下文件供账户核准使用：",
    "help-pending-jp": "您的账户尚未得到核准。请上传以下文件供账户核准使用：",
    "help-pending-jp-link": "文件说明",
    "help-banned": "请您尽快联系我们 support@quoine.com",
    "help-edit-info": "如果更改用户信息请联系我们（support@quoine.com）",
    // ===
    "document-id": "身份文件",
    "document-id-help": "",
    "document-address": "地址证明",
    "document-address-help": "",
    "document-bank": "银行账单",
    "document-bank-help": "",
    "document-action": "提交文件",
    // ===
    "id": "用户身份",
    "first-name": "名",
    "last-name": "姓",
    "email": "电子邮件",
    "since": "注册日",
    "affiliate-code": "联盟代码",
  },
  "user-error": {
    "invalid-types": "请检查您的文件格式，允许以下文件格式：pdf、xps、jpg、jpeg、png 和 gif",
  },
  "edit-user": {
    "title": "更新用户资料",
    "action": "更新用户资料",
    "action-submit": "提交",
    "action-cancel": "取消",
    "description": "如果您成为美国公民，将适用不同的 KYC/AML 规定，请通过 support@quoine.com 联系我们",
    "message-no-changes": "没有完成更新资料过程",
  },
  "tfa-manage": {
    "status": "TFA Status",
    "status-enabled": "启用",
    "status-not-enabled": "尚未启用",
    // ===
    "app-select-description": "请从下面的途径中选择双重认证应用:",
    // ===
    "app": "TFA App",
    "app-authy": "Authy",
    "app-ga": "Google Authenticator",
    // ===
    "action-enable": "启用",
    "action-disable": "禁用",
    // ===
    "form-input": "验证码",
    "form-authy-description": "请输入发送至您电话的代码。",
    "form-ga-description": "请使用Google Authenticator获得您的验证码。",
  },
  "tfa-manage-error": {
    "en-authy-verification-failed": "验证码不能为空",
    "verification-failed": "验证码不能为空",
    "en-authy-token-is-blank": "验证码不能为空",
    "token-is-invalid": "验证码无效",
  },
  "tfa-phone": {
    "phone": "电话",
    "help-change-phone": "如需更改电话号码，请通过 support@quoine.com 联系我们",
    // ===
    "add-phone-title": "添加电话号码",
    "add-phone-action": "添加",
    "add-phone-label": "电话号码",
    "add-phone-description": "请输入电话号码",
  },
  "tfa-ga": {
    "scan-barcode": "请使用Google Authenticator扫描QR code。",
    "enter-code": "请输入Google Authenticator提示的六位验证码。",
    "enter-code-description": "当您扫描提示的QR code后，Google Authenticator将会提供您需要输入的六位的验证码:",
    "enter-key-description": "您也可以选择手动输入来代替扫描QR code。",
  },
  "token": {
    "id": "编号",
    "value": "密钥",
    "value-copy": "复制",
    "permissions": "权限",
    "none": "无",
    "value-message": "本验证码只提示一次",
    // ===
    "remove-title": "删除密钥",
    "remove-action": "删除",
    "remove-description": "您确定要删除此密钥吗？使用该密钥的所有设备和应用程序都将立即失去授权",
    // ===
    "add-title": "创建新的密钥",
    "add-description": "请为新密钥选择许可权限：",
    "add-action-submit": "创建密钥",
    "add-action-cancel": "取消",
    // ===
    "action-r": "读取",
    "action-w": "写入",
    // ===
    "name-accounts": "账户",
    "name-executions": "执行",
    "name-orders": "订单",
    "name-trades": "仓位",
    "name-trading-accounts": "交易账户",
  },
};
