/* eslint-disable quotes, quote-props, max-len */

// quoine

export default {
  "sign-in": {
    "title": "登錄",
    "action": "登錄",
    "email": "郵箱地址",
    "password": "密碼",
    "code": "驗證碼",
    "code-description": "需要驗證碼才能登錄，該驗證碼已通過 Authy 或短信發送至您的手機",
    "back": "返回",
    "new-text": "沒有賬戶",
    "new-or": "或者",
    // message
    "message-account-confirmed": "賬戶已確認，您現在可以登錄",
    "message-password-updated": "密碼已更新，請使用新密碼登錄",
    "message-signed-out": "已登出",
    "message-need-sign-in": "請先登錄",
  },
  "sign-in-error": {
    "you-have-to-confirm-your-account-before-continuing": "請先確認您的賬戶",
    "your-password-is-incorrect": "密碼不正確",
    "token-is-invalid": "驗證碼無效",
    "invalid-email-or-password": "郵箱地址或密碼無效",
    "verification-failed": "驗證碼無效",
    "you-are-logging-in-from-a-new-ip-address-that-is-not-confirmed-yet-a-confirmation-link-has-been-sent-to-your-email-address-please-check-and-confirm-to-continue": "本次登陸的IP地址尚未被驗證，驗證鏈接已經發送到您的郵箱，請查收",
  },
  "forgot-password": {
    "action-resend": "重新發送密碼重置鏈接",
    "action-send": "發送密碼重置鏈接",
    "description": "請輸入您的郵箱地址收取密碼重置鏈接",
    "title": "忘記密碼",
    "message-sent": "密碼重置鏈接已發送，請在點擊鏈接後繼續操作。密碼重置鏈接十分鐘內有效",
    "email": "郵箱地址",
  },
  "forgot-password-error": {
    "email-not-found": "未找到郵箱地址",
    "email-can-t-be-blank": "郵箱地址不能為空",
  },
  "reset-password": {
    "new-password": "新密碼",
    "new-password-help": "密碼至少包含 8 個字符並且包含至少 1 個小寫字母、1 個大寫字母和 1 個數字",
    "token": "重置驗證碼",
    "token-help": "請輸入已發送到您郵箱中的重置驗證碼",
    "action": "更新密碼",
    "title": "重置密碼",
  },
  "reset-password-error": {
    "reset-password-token-can-t-be-blank": "驗證碼不能為空，請輸入發送到您郵箱的驗證碼",
    "reset-password-token-is-invalid": "驗證碼無效，請輸入發送到您郵箱的驗證碼",
    "reset-password-token-expired": "重置密碼嘗試已過期。請返回首頁並重試",
    "password-is-too-short-minimum-is-8-characters": "密碼必須包含 8 個字符並且包含至少 1 個小寫字母、1 個大寫字母和 1 個數字",
  },
  "change-password": {
    "title": "更改密碼",
    "action-submit": "更改",
    "action-cancel": "取消",
    "action-done": "完成",
    "input-next": "新密碼",
    "input-current": "原密碼",
    "success": "密碼已成功更新",
    "password-help": "密碼必須至少包含 8 個字符並且包含至少 1 個小寫字母、1 個大寫字母和 1 個數字",
  },
  "change-password-error": {
    "password-update-failed": "密碼更新失敗",
    "your-password-is-incorrect": "您的密碼不正確",
  },
  "sign-up": {
    "title": "註冊",
    "action-next": "下一項",
    "action-done": "完成",
    "action-sign-in": "轉至登錄頁",
    "back": "返回",
    // ===
    "message-success": "感謝您的註冊，驗證鏈接將發送至您的郵箱",
    // ===
    "step-1": "1. 賬戶類型",
    "step-2": "2. 賬戶概覽",
    "step-3": "3. 賬戶詳情",
    "step-4": "4. 條款聲明",
    // ===
    "type-corporate-title": "公司",
    "type-corporate-description": "註冊賬戶將用於公司",
    "type-individual-title": "個人",
    "type-individual-description": "註冊賬戶將用於個人",
    // ===
    "email": "電子郵件",
    "email-help": "此電子郵件將用於登錄您的賬戶",
    "password": "密碼",
    "password-help": "密碼必須至少包含 8 個字符並且包含至少 1 個小寫字母、1 個大寫字母和 1 個數字",
    "country": "居住國",
    "country-sure": "確認居住國",
    "country-sure-help": "如有變更，請在變更日起 3 個月內聯系我們",
    "us": "美國納稅義務",
    "us-no": "否",
    "us-yes": "是",
    "us-help": "如果您是\"美國公民\"或\"美國居民（在美國有永久居留權的人，在美國居住超過 183 天的人\"），請選擇\"是\"",
    "referral": "促銷碼（選填）",
    "term-quoine": "我同意<a href=\"https://www.quoine.com/terms\" target=\"_blank\">條款聲明</a>",
    "term-traders": "我同意<a href=\"https://min-btc.com/terms\" target=\"_blank\">條款聲明</a>",
    "term-qryptos": "我同意<a href=\"https://s3-ap-northeast-1.amazonaws.com/jfsa-qryptos/Terms+and+Conditions+QUOINE+PTE+LTD_V1.0.pdf\" target=\"_blank\">條款聲明</a>",
  },
  "sign-up-pi": {
    "name": "姓名",
    "nationality": "國籍",
    "address": "地址",
    "birth": "生日",
    "income": "主要收入來源",
    "income-employed": "就業",
    "income-other": "其他",
    "income-retired": "退休",
    "income-self-employed": "個體營業",
    "income-job": "職位",
    "income-business-name": "企業名稱",
    "income-business-type": "企業類型",
    "income-detail": "詳述收入來源",
  },
  "sign-up-pc": {
    "name": "企業名稱",
    "type": "企業類型",
    "address": "地址",
    "website": "網站",
    "tax-id": "TAX",
    "vat-id": "VAT",
  },
  "sign-up-error": {
    "email-has-already-been-taken": "此電子郵件已被占用",
    "all-is-required": "所有字段都為必填項",
    "terms": "請仔細閱讀條款聲明，然後繼續",
    "password-is-too-short-minimum-is-8-characters": "密碼必須至少包含 8 個字符並且包含至少 1 個小寫字母、1 個大寫字母和 1 個數字",
    "qryptos-not-available-for-japanese": "QRYPTOS暫時不支援日語服務，敬請見諒。",
  },
  "demo": {
    "title": "模擬賬戶",
    "email": "電子郵件",
    "action": "進入模擬模式",
    // ===
    "continue-title": "繼續您的模擬模式",
    "continue-overview": "使用之前的模擬賬戶繼續您的交易",
    "continue-description": "請輸入希望恢復的模擬賬戶的郵箱地址",
    "continue-found": "下方是您在此瀏覽器上最後一次模擬會話所用的地址",
    // ===
    "new-title": "開始新的模擬",
    "new-overview": "創建一個新的模擬賬戶並試用應用及其功能",
    "new-description": "下方郵箱地址將用於為您創建一個模擬賬戶，您可通過所支持的系統和瀏覽器訪問此模擬賬戶",
  },
  "sign-out": {
    "action": "登出",
    "description": "點擊登出交易系統。當關閉標簽頁時也將自動登出。<br /><br />如要結束所有設備和瀏覽器中登錄，請勾選下方選框",
    "all": "登出所有",
    "title": "您要登出嗎？",
  },
  "settings": {
    "title": "設置",
    "back-to-trading": "返回交易",
    // ===
    "application-title": "申請",
    "theme-title": "主題",
    // ===
    "profile-title": "個人資料",
    // ===
    "security-title": "安全",
    "password-title": "密碼",
    "tfa-title": "雙重驗證",
    // ===
    "api-title": "API接口",
  },
  "daily-report": {
    "title": "日報",
    "label": "接收日報",
  },
  "user": {
    "verification": "審查",
    // ===
    "status": "狀態",
    "status-documents-submitted": "文件已提交",
    "status-approved": "已核准",
    "status-declined": "已拒絕",
    "status-pending": "待定",
    "status-banned": "被禁止",
    // ===
    "help-documents-submitted": "您的文件已上傳，我們的員工將盡快審查並核準您的賬戶。賬戶核查過程需要 1-2 個工作日",
    "help-approved": "您的賬戶已被核准，無需進一步操作",
    "help-declined": "您的賬戶核準請求已被拒絕。請更新您的文件：{{ reason }}.",
    "help-pending": "您的賬戶尚未得到核準。請上傳以下文件供賬戶核準使用：",
    "help-pending-jp": "您的賬戶尚未得到核準。請上傳以下文件供賬戶核準使用：",
    "help-pending-jp-link": "文件說明",
    "help-edit-info": "如果更改用戶信息請聯系我們（support@quoine.com）",
    // ===
    "document-id": "身份文件",
    "document-id-help": "",
    "document-address": "地址證明",
    "document-address-help": "",
    "document-bank": "銀行賬單",
    "document-bank-help": "",
    "document-action": "提交文件",
    // ===
    "id": "用戶身份",
    "first-name": "名",
    "last-name": "姓",
    "email": "電子郵件",
    "since": "註冊日",
    "affiliate-code": "聯盟代碼",
  },
  "user-error": {
    "invalid-types": "請檢查您的文件格式，允許以下文件格式：pdf、xps、jpg、jpeg、png 和 gif",
  },
  "edit-user": {
    "title": "更新用戶資料",
    "action": "更新用戶資料",
    "action-submit": "提交",
    "action-cancel": "取消",
    "description": "如果您成為美國公民，將適用不同的 KYC/AML 規定，請通過 support@quoine.com 聯系我們",
    "message-no-changes": "沒有完成更新資料過程",
  },
  "tfa-manage": {
    "status": "TFA Status",
    "status-enabled": "啟用",
    "status-not-enabled": "尚未啟用",
    // ===
    "app-select-description": "To enabled 2FA, please select one of the apps below:",
    // ===
    "app": "TFA App",
    "app-authy": "Authy",
    "app-ga": "Google Authenticator",
    // ===
    "action-enable": "啟用",
    "action-disable": "禁用",
    // ===
    "form-input": "驗證碼",
    "form-authy-description": "請輸入發送至您電話的代碼。",
    "form-ga-description": "Please open your Google Authenticator app to get your auth code.",
  },
  "tfa-manage-error": {
    "en-authy-token-is-blank": "驗證碼不能為空",
    "verification-failed": "Token is invalid.",
    "en-authy-token-is-blank": "Authentication code is required.",
    "token-is-invalid": "驗證碼無效",
  },
  "tfa-phone": {
    "phone": "電話",
    "help-change-phone": "如需更改電話號碼，請通過 support@quoine.com 聯系我們",
    // ===
    "add-phone-title": "添加電話號碼",
    "add-phone-action": "添加",
    "add-phone-label": "電話號碼",
    "add-phone-description": "請輸入電話號碼",
  },
  "tfa-ga": {
    "scan-barcode": "Scan this QR code with Google Authenticator.",
    "enter-code": "Enter the six-digit code provided by the app.",
    "enter-code-description": "Once you have scanned the QR code, the app will provide a six-digit code which you can enter in the field below:",
    "enter-key-description": "You can also choose Manual Entry and enter the key yourself instead of scanning the QR code.",
  },
  "token": {
    "id": "編號",
    "value": "密鑰",
    "value-copy": "復制",
    "permissions": "權限",
    "none": "無",
    "value-message": "本驗證碼只提示一次",
    // ===
    "remove-title": "刪除密鑰",
    "remove-action": "刪除",
    "remove-description": "您確定要刪除此密鑰嗎？使用該密鑰的所有設備和應用程序都將立即失去授權",
    // ===
    "add-title": "創建新的密鑰",
    "add-description": "請為新密鑰選擇許可權限：",
    "add-action-submit": "創建密鑰",
    "add-action-cancel": "取消",
    // ===
    "action-r": "讀取",
    "action-w": "寫入",
    // ===
    "name-accounts": "賬戶",
    "name-executions": "執行",
    "name-orders": "訂單",
    "name-trades": "倉位",
    "name-trading-accounts": "交易賬戶",
  },
};
