/* eslint-disable quotes, quote-props, max-len */

// quoine

export default {
  "sign-in": {
    "title": "登錄",
    "action": "登錄",
    "email": "電子郵件地址",
    "password": "密碼",
    "code": "驗證碼",
    "code-description": "需要驗證碼才能登錄。該驗證碼已通過 Authy 或短信發送至您的手機。",
    "back": "返回",
    "new-text": "沒有賬戶？",
    "new-or": "或者",
    // message
    "message-account-confirmed": "您的賬戶已確認。您現在可以登錄。",
    "message-password-updated": "您的密碼已更新。您現在可以使用新密碼登錄。",
    "message-signed-out": "您已經登出。",
    "message-need-sign-in": "請先登錄。",
  },
  "sign-in-error": {
    "you-have-to-confirm-your-account-before-continuing": "請確認您的賬戶後再繼續。",
    "your-password-is-incorrect": "您的密碼不正確。",
    "token-is-invalid": "代碼無效。",
    "invalid-email-or-password": "電子郵件地址或密碼無效。",
    "verification-failed": "驗證碼無效。",
  },
  "forgot-password": {
    "action-resend": "重新發送密碼重置鏈接",
    "action-send": "發送密碼重置鏈接",
    "description": "請輸入您的電子郵件地址以收取密碼重置鏈接。",
    "title": "忘記密碼？",
    "message-sent": "密碼重置鏈接已發送。請在您的收件箱和/或垃圾箱找到該鏈接後繼續操作。如果10 分鐘後仍未看到我們的電子郵件，請點擊重新發送。",
    "email": "電子郵件地址",
  },
  "forgot-password-error": {
    "email-not-found": "未找到電子郵件地址。",
    "email-can-t-be-blank": "電子郵件地址必填。",
  },
  "reset-password": {
    "new-password": "新密碼",
    "new-password-help": "密碼必須至少包含 8 個字符並且包含至少 1 個小寫字母、1 個大寫字母和 1 個數字。",
    "token": "Reset Token",
    "token-help": "Please enter the reset token that was sent to your email address.",
    "action": "更新密碼",
    "title": "重置密碼",
  },
  "reset-password-error": {
    "reset-password-token-can-t-be-blank": "Token is required. Please enter the reset token that was sent to your email address.",
    "reset-password-token-is-invalid": "Token is invalid. Please enter the reset token that was sent to your email address.",
    "reset-password-token-expired": "重置密碼嘗試已過期。請返回首頁並重試。",
    "password-is-too-short-minimum-is-8-characters": "密碼必須至少包含 8 個字符並且包含至少 1 個小寫字母、1 個大寫字母和 1 個數字。",
  },
  "change-password": {
    "title": "更改密碼",
    "action-submit": "更改",
    "action-cancel": "取消",
    "action-done": "完成",
    "input-next": "新密碼",
    "input-current": "現有密碼",
    "success": "您的密碼已成功更新。",
  },
  "change-password-error": {
    "password-update-failed": "密碼更新失敗。",
    "your-password-is-incorrect": "您的密碼不正確。",
  },
  "sign-up": {
    "title": "註冊",
    "action-next": "下一項",
    "action-done": "完成",
    "action-sign-in": "轉至登錄頁",
    "back": "返回",
    // ===
    "message-success": "感謝您註冊。整個過程已接近完成！進一步指示將發送至您的電子郵件地址。",
    // ===
    "step-1": "1. 賬戶類型",
    "step-2": "2. 賬戶概覽",
    "step-3": "3. 賬戶詳情",
    "step-4": "4. 條款及條件",
    // ===
    "type-corporate-title": "公司",
    "type-corporate-description": "註冊賬戶將用於公司。",
    "type-in​​dividual-title": "個人",
    "type-in​​dividual-description": "註冊賬戶將用於個人。",
    // ===
    "email": "電子郵件",
    "email-help": "此電子郵件將用於登錄您的賬戶。",
    "password": "密碼",
    "password-help": "密碼必須至少包含 8 個字符並且包含至少 1 個小寫字母、1 個大寫字母和 1 個數字。",
    "country": "居住國",
    "country-sure": "我確認我住在日本。",
    "country-sure-help": "如有任何變更，請在變更日起 3 個月內告知該變更情況。",
    "us": "美國納稅義務",
    "us-no": "否",
    "us-yes": "是",
    "us-help": "如果您是\"美國公民\"或\"美國居民（在美國有永久居留權的人，在美國居住超過183 天的人\"），請選擇\"是\" 。",
    "referral": "促銷碼（選填）",
    "term-quoine": "我同意<a href=\"https://www.quoine.com/terms\" target=\"_blank\">條款及條件</a>。",
    "term-traders": "我同意<a href=\"https://min-btc.com/terms\" target=\"_blank\">條款及條件</a>。",
  },
  "sign-up-pi": {
    "name": "姓名",
    "nationality": "國籍",
    "address": "地址",
    "birth": "生日",
    "income": "主要收入來源",
    "income-employed": "就業",
    "income-other": "其他",
    "income-retired": "退休",
    "income-self-employed": "自僱業者",
    "income-job": "職位",
    "income-business-name": "企業名稱",
    "income-business-type": "企業類型",
    "income-detail": "收入來源詳情",
  },
  "sign-up-pc": {
    "name": "企業名稱",
    "type": "企業類型",
    "address": "地址",
    "website": "網站",
    "tax-id": "TAX",
    "vat-id": "VAT",
  },
  "sign-up-error": {
    "email-has-already-been-taken": "此電子郵件已被佔用。",
    "all-is-required": "所有字段都為必填項。",
    "terms": "請仔細閱讀條款及條件並在接受它們後再繼續。",
    "password-is-too-short-minimum-is-8-characters": "密碼必須至少包含 8 個字符並且包含至少 1 個小寫字母、1 個大寫字母和 1 個數字。",
  },
  "demo": {
    "title": "使用演示賬戶",
    "email": "演示賬戶電子郵件",
    "action": "進入演示模式",
    // ===
    "continue-title": "繼續您的演示",
    "continue-overview": "使用您之前的演示賬戶繼續您的交易進程。",
    "continue-description": "請輸入您希望恢復的演示賬戶的電子郵件地址。",
    "continue-found": "下方是您在此瀏覽器上最後一次演示會話所用的地址。",
    // ===
    "new-title": "開始新的演示",
    "new-overview": "創建一個新的演示賬戶並儘情試用我們的應用及其功能！",
    "new-description": "下方電子郵件地址將用於為您創建一個演示賬戶。您可通過所有支持的系統和瀏覽器訪問此演示賬戶，只要使用此地址恢復操作即可。",
  },
  "sign-out": {
    "action": "登出",
    "description": "點擊登出以結束您在此標籤頁中的會話。當您關閉標籤頁時您也將自動登出。<br /><br />如要結束您在所有設備和瀏覽器中的會話，請勾選下方方框。",
    "all": "結束所有會話",
    "title": "您要登出嗎？",
  },
  "settings": {
    "title": "設置",
    "back-to-trading": "返回交易",
    // ===
    "application-title": "申請",
    "theme-title": "主題",
    // ===
    "profile-title": "個人資料",
    // ===
    "security-title": "安全",
    "password-title": "密碼",
    "sign-in-title": "登錄",
    // ===
    "api-title": "應用程序界面",
  },
  "daily-report": {
    "title": "報告",
    "label": "接收每日報告",
  },
  "user": {
    "verification": "核驗",
    // ===
    "status": "狀態",
    "status-documents-submitted": "文件已提交",
    "status-approved": "已批准",
    "status-declined": "已拒絕",
    "status-pending": "待定",
    // ===
    "help-documents-submitted": "您的文件已上傳。我們的員工將很快審閱並批准您的賬戶。請注意賬戶核驗過程需要 1-2 個工作日。",
    "help-approved": "您的賬戶已被批准。無需進一步操作。",
    "help-declined": "您的賬戶核准請求已被拒絕。請注意以下指示並更新您的文件：{{ reason }}.",
    "help-pending": "您的賬戶尚未得到核准。請上傳以下文件供賬戶核准使用：",
    "help-pending-jp": "您的賬戶尚未得到核准。請上傳以下文件供賬戶核准使用：",
    "help-pending-jp-link": "文件說明",
    // ===
    "document-id": "身份文件",
    "document-id-help": "",
    "document-address": "地址證明",
    "document-address-help": "",
    "document-bank": "銀行賬單",
    "document-bank-help": "",
    "document-action": "提交文件",
    // ===
    "id": "用戶身份",
    "first-name": "名",
    "last-name": "姓",
    "email": "電子郵件",
    "since": "註冊日",
    "affiliate-code": "聯盟代碼",
  },
  "user-error": {
    "invalid-types": "請檢查您的文件類型。允許以下類型：pdf、xps、jpg、jpeg、png 和 gif。",
  },
  "edit-user": {
    "title": "更新用戶個人資料",
    "action": "更新用戶個人資料",
    "action-submit": "提交",
    "action-cancel": "取消",
    "description": "如果您成為美國公民，將適用不同的 KYC/AML 規定，因此請通過 support@quoine.com 聯繫我們。",
    "message-no-changes": "Your information has not been changed.",
  },
  "tfa-manage": {
    "phone": "電話",
    "title": "雙重驗證",
    "status-enabled": "啟用",
    "status-not-enabled": "尚未啟用",
    // ===
    "help-change-phone": "如要更改您的電話號碼，請通過 support@quoine.com 聯繫我們的支持人員。",
    // ===
    "add-phone-title": "添加電話號碼",
    "add-phone-action": "添加",
    "add-phone-label": "電話號碼",
    "add-phone-description": "請輸入新的電話號碼。",
    // ===
    "toggle-title-enable": "啟用",
    "toggle-title-disable": "禁用",
    "toggle-action-enable": "啟用",
    "toggle-action-disable": "禁用",
    "toggle-description": "請輸入發送至您電話的代碼。",
    "toggle-label": "驗證碼",
    // ===
    "action-cancel": "取消",
    "action-done": "確認",
  },
  "tfa-manage-error": {
    "en-authy-token-is-blank": "驗證碼為必填項。",
    "token-is-invalid": "令牌無效。",
  },
  "token": {
    "id": "編號",
    "value": "令牌/密鑰",
    "value-copy": "複製",
    "permissions": "權限",
    "none": "無",
    "value-message": "This Token/Secret is displayed one time only.",
    // ===
    "remove-title": "刪除令牌",
    "remove-action": "刪除",
    "remove-description": "您確定要刪除此令牌嗎？使用該令牌的所有設備和應用程序都將立即失去授權。",
    // ===
    "add-title": "創建新的 API 令牌",
    "add-description": "請為新令牌選擇許可權限：",
    "add-action-submit": "創建令牌",
    "add-action-cancel": "取消",
    // ===
    "action-r": "讀取",
    "action-w": "寫入",
    // ===
    "name-accounts": "賬戶",
    "name-executions": "執行",
    "name-orders": "訂單",
    "name-trades": "倉位",
    "name-trading-accounts": "交易賬戶",
  },
};
