{  
  "id":9390,
  "email":"huong.quoine+13@gmail.com",
  "ext_id":null,
  "first_name":"",
  "last_name":"",
  "name":"",
  "avatar":null,
  "currency":"JPY",
  "status":"pending",
  "declined_reason":null,
  "recent_addresses":{  
    "ETH":[  

    ],
    "BTC":[  

    ]
  },
  "is_maker":false,
  "country":"JP",
  "language":"en",
  "id_document_filename":null,
  "proof_address_filename":null,
  "bank_statement_filename":null,
  "created_at":1489585639,
  "settings":{  

  },
  "currencies":[  
    "JPY",
    "USD",
    "ETH",
    "BTC"
  ],
  "affiliate_code":"c9KdNYPJ9390",
  "pusher_channel":"user_9390",
  "signed_for_bonus_campaign":false,
  "custom_fees":{  

  },
  "phone":null,
  "phone_verified":false,
  "is_fully_verified":false,
  "receive_report":false,
  "no_password":false,
  "bank_accounts":[  

  ],
  "nationality":null,
  "country_name":"Japan",
  "nationality_name":null,
  "user_setting":{  
    "created_at":"2017-03-15T13:47:20Z",
    "id":9102,
    "receive_report":false,
    "updated_at":"2017-03-15T13:50:19Z",
    "user_id":9390,
    "web_app_setting":"{\"current\":{},\"confirmation\":{},\"layout\":{},\"filters\":{},\"blottersVertical\":{},\"blottersHorizontal\":{},\"confirmations\":{\"skips\":[]},\"languages\":{\"current\":\"en\"},\"themes\":{\"current\":\"light\"},\"notifications\":{\"dismissed\":[]},\"tabs\":{}}"
  },
  "user_type":"corporate",
  "address":null,
  "user_profile":null,
  "app_vendor_id":9373,
  "individual_info":null,
  "corporation_info":{  
    "industry_type":"情報・通信",
    "business":null,
    "established_date":0,
    "annual_report_date":0,
    "corporate_name":"Quoine",
    "corporate_kana_name":"フリガナ",
    "address":{  
      "zip":"1111111",
      "street":"d",
      "building":"",
      "prefecture":"ddd",
      "municipality":"dd"
    },
    "phone":"1",
    "website":"d",
    "income_gross":"30万円～100万円未満",
    "income_net":"250万円～500万円未満",
    "capital":"100万円～250万円未満",
    "invest_purpose":{  
      "trade":"true",
      "invest":"true",
      "exchange":"true",
      "diversify":"true"
    },
    "experience":{  
      "fx":"5年未満",
      "margin":"5年未満",
      "option":"5年未満",
      "stocks":"5年未満",
      "commodities":"4年未満"
    },
    "relation":{  
      "type":"当社ホームページ",
      "detail":""
    },
    "corporation_user_infos":[  
      {  
        "user_info_type":"representative",
        "title":"d",
        "gender":null,
        "first_kanji_name":"代表者氏名",
        "last_kanji_name":"代表者氏名",
        "first_kana_name":"フリガナ",
        "last_kana_name":"フリガナ",
        "is_us_citizen":true,
        "is_living_in_jp":true,
        "is_pep":true,
        "business_type":null,
        "business_name":null,
        "position":null,
        "shareholder_type":null,
        "birthdate":null,
        "department":null,
        "address":{  

        },
        "phone":null,
        "email":null
      },
      {  
        "user_info_type":"trader",
        "title":null,
        "gender":"男性",
        "first_kanji_name":"氏名",
        "last_kanji_name":"氏名",
        "first_kana_name":"フリガナ",
        "last_kana_name":"フリガナ",
        "is_us_citizen":false,
        "is_living_in_jp":true,
        "is_pep":true,
        "business_type":null,
        "business_name":null,
        "position":"フリガナ",
        "shareholder_type":null,
        "birthdate":null,
        "department":"フリガナ",
        "address":{  
          "zip":"1111111",
          "street":"フリガナ",
          "building":"",
          "prefecture":"フリガナ",
          "municipality":"フリガナ"
        },
        "phone":"1",
        "email":"abc@gmail.com"
      }
    ]
  }
}