{  
  "id":9400,
  "email":"huong.quoine+20@gmail.com",
  "ext_id":null,
  "first_name":"",
  "last_name":"",
  "name":"",
  "avatar":null,
  "currency":"JPY",
  "status":"pending",
  "declined_reason":null,
  "recent_addresses":{  
    "ETH":[  

    ],
    "BTC":[  

    ]
  },
  "is_maker":false,
  "country":"JP",
  "language":"en",
  "id_document_filename":null,
  "proof_address_filename":null,
  "bank_statement_filename":null,
  "created_at":1489593435,
  "settings":{  

  },
  "currencies":[  
    "JPY",
    "USD",
    "ETH",
    "BTC"
  ],
  "affiliate_code":"fAFaRPui9400",
  "pusher_channel":"user_9400",
  "signed_for_bonus_campaign":false,
  "custom_fees":{  

  },
  "phone":"0839234982",
  "phone_verified":false,
  "is_fully_verified":false,
  "receive_report":false,
  "no_password":false,
  "bank_accounts":[  

  ],
  "nationality":null,
  "country_name":"Japan",
  "nationality_name":null,
  "user_setting":{  
    "created_at":"2017-03-15T15:57:15Z",
    "id":9109,
    "receive_report":false,
    "updated_at":"2017-03-15T15:57:15Z",
    "user_id":9400,
    "web_app_setting":null
  },
  "user_type":"corporate",
  "address":null,
  "user_profile":null,
  "app_vendor_id":9373,
  "individual_info":null,
  "corporation_info":{  
    "industry_type":"情報・通信",
    "business":null,
    "established_date":694224000,
    "annual_report_date":5097600,
    "corporate_name":"法人名",
    "corporate_kana_name":"フリガナ",
    "address":{  
      "zip":"7000000",
      "street":"ご住所",
      "building":"ご住所",
      "prefecture":"ご住所",
      "municipality":"ご住所"
    },
    "phone":"0839234982",
    "website":"ご住所",
    "income_gross":"30万円～100万円未満",
    "income_net":"30万円～100万円未満",
    "capital":"30万円～100万円未満",
    "invest_purpose":{  
      "trade":"true",
      "invest":"true",
      "exchange":"true",
      "diversify":"true"
    },
    "experience":{  
      "fx":"5年以上",
      "margin":"4年未満",
      "option":"5年未満",
      "stocks":"5年未満",
      "commodities":"5年未満"
    },
    "relation":{  
      "type":"当社ホームページ",
      "detail":""
    },
    "corporation_user_infos":[  
      {  
        "user_info_type":"representative",
        "title":"ご住所",
        "gender":null,
        "first_kanji_name":"代表者氏名",
        "last_kanji_name":"代表者氏名",
        "first_kana_name":"フリガナ",
        "last_kana_name":"フリガナ",
        "is_us_citizen":true,
        "is_living_in_jp":true,
        "is_pep":true,
        "business_type":null,
        "business_name":null,
        "position":null,
        "shareholder_type":null,
        "birthdate":null,
        "department":null,
        "address":{  

        },
        "phone":null,
        "email":null
      },
      {  
        "user_info_type":"trader",
        "title":null,
        "gender":"男性",
        "first_kanji_name":"担当者役職名",
        "last_kanji_name":"担当者役職名",
        "first_kana_name":"フリガナ",
        "last_kana_name":"フリガナ",
        "is_us_citizen":false,
        "is_living_in_jp":true,
        "is_pep":true,
        "business_type":null,
        "business_name":null,
        "position":"担当者役職名",
        "shareholder_type":null,
        "birthdate":null,
        "department":"担当者役職名",
        "address":{  
          "zip":"8000000",
          "street":"ご住所",
          "building":"",
          "prefecture":"ご住所",
          "municipality":"ご住所"
        },
        "phone":"0820239322",
        "email":"abc@quoine.add"
      },
      {  
        "user_info_type":"shareholder",
        "title":null,
        "gender":null,
        "first_kanji_name":"漢字",
        "last_kanji_name":"漢字",
        "first_kana_name":"カナ",
        "last_kana_name":"カナ",
        "is_us_citizen":true,
        "is_living_in_jp":true,
        "is_pep":true,
        "business_type":"議決権が50％を超える個人",
        "business_name":"株式会社",
        "position":null,
        "shareholder_type":null,
        "birthdate":"1970-01-01",
        "department":null,
        "address":{  
          "zip":"8202002",
          "street":"ご住所",
          "building":"",
          "prefecture":"ご住所",
          "municipality":"ご住所"
        },
        "phone":null,
        "email":null
      },
      {  
        "user_info_type":"shareholder",
        "title":null,
        "gender":null,
        "first_kanji_name":"漢字",
        "last_kanji_name":"漢字",
        "first_kana_name":"カナ",
        "last_kana_name":"カナ",
        "is_us_citizen":true,
        "is_living_in_jp":true,
        "is_pep":true,
        "business_type":"議決権が50％を超える個人",
        "business_name":"株式会社",
        "position":null,
        "shareholder_type":null,
        "birthdate":"1970-01-01",
        "department":null,
        "address":{  
          "zip":"8000000",
          "street":"ご住所",
          "building":"ご住所",
          "prefecture":"ご住所",
          "municipality":"ご住所ご住所"
        },
        "phone":null,
        "email":null
      }
    ]
  }
}