{  
  "id":9387,
  "email":"huong.quoine+11@gmail.com",
  "ext_id":null,
  "first_name":"",
  "last_name":"",
  "name":"",
  "avatar":null,
  "currency":"JPY",
  "status":"pending",
  "declined_reason":null,
  "recent_addresses":{  
    "ETH":[  

    ],
    "BTC":[  

    ]
  },
  "is_maker":false,
  "country":"JP",
  "language":"en",
  "id_document_filename":null,
  "proof_address_filename":null,
  "bank_statement_filename":null,
  "created_at":1489566789,
  "settings":{  

  },
  "currencies":[  
    "JPY",
    "USD",
    "ETH",
    "BTC"
  ],
  "affiliate_code":"a9XMAm0i9387",
  "pusher_channel":"user_9387",
  "signed_for_bonus_campaign":false,
  "custom_fees":{  

  },
  "phone":"81-01666322395",
  "phone_verified":false,
  "is_fully_verified":false,
  "receive_report":false,
  "no_password":false,
  "bank_accounts":[  

  ],
  "nationality":null,
  "country_name":"Japan",
  "nationality_name":null,
  "user_setting":{  
    "created_at":"2017-03-15T08:33:09Z",
    "id":9099,
    "receive_report":false,
    "updated_at":"2017-03-15T12:54:12Z",
    "user_id":9387,
    "web_app_setting":"{\"current\":{},\"confirmation\":{},\"layout\":{},\"filters\":{},\"blottersVertical\":{},\"blottersHorizontal\":{},\"confirmations\":{\"skips\":[]},\"languages\":{\"current\":\"en\"},\"themes\":{\"current\":\"light\"},\"notifications\":{\"dismissed\":[]},\"accounts\":{\"hiddens\":[]},\"mrgAccs\":{\"hiddens\":[]},\"trading\":{\"account\":\"USD\",\"product\":\"BTCUSD\",\"market\":\"margin\"},\"panels\":{\"prefs\":[{\"order\":0,\"grow\":0},{\"order\":1,\"grow\":0},{\"order\":2,\"grow\":1},{\"order\":3,\"grow\":0},{\"order\":4,\"grow\":-1},{\"order\":5,\"grow\":-1},{\"order\":6,\"grow\":-1},{\"order\":7,\"grow\":-1}]},\"tabs\":{},\"orderBlotter\":{\"filters\":{\"status\":\"all\",\"side\":\"all\"}},\"positionBlotter\":{\"filters\":{\"status\":\"all\",\"side\":\"all\"}},\"executionBlotter\":{\"filters\":{\"side\":\"all\"}},\"orderEntry\":{\"form\":{\"type\":\"market\",\"quantity\":\"1\",\"quantityDisclose\":\"1\",\"price\":\"1\",\"side\":\"buy\",\"leverage\":2,\"direction\":\"one-direction\",\"slippage\":false,\"slippageValue\":\"100\",\"distance\":\"50\",\"distanceType\":\"fiat\"}},\"nextCharts\":{}}"
  },
  "user_type":"individual",
  "address":null,
  "user_profile":null,
  "app_vendor_id":9373,
  "individual_info":{  
    "first_kanji_name":"漢字",
    "last_kanji_name":"漢字",
    "first_kana_name":"カナ",
    "last_kana_name":"カナ",
    "gender":"女性",
    "birthdate":"1970-01-01",
    "is_us_resident":null,
    "is_jp_resident":null,
    "is_pep":false,
    "address":{  
      "zip":"0000000",
      "street":"カナ",
      "building":"カナ",
      "prefecture":"カナ",
      "municipality":"カナ"
    },
    "work_address":{  
      "zip":"0000000",
      "street":"カナ",
      "building":"",
      "prefecture":"カナ",
      "municipality":"カナ"
    },
    "occupation":{  
      "job":"会社員",
      "detail":"",
      "industry":"林業"
    },
    "work_phone":"1",
    "income_source":"事業所得",
    "income_amount":"30万円～100万円未満",
    "invest_permission":false,
    "investable_amount":100.0,
    "phone":null,
    "work_place_name":null,
    "invest_purpose":{  
      "trade":"true",
      "invest":"true",
      "exchange":"true",
      "diversify":"true"
    },
    "experience":{  
      "fx":"5年未満",
      "margin":"4年未満",
      "option":"5年未満",
      "stocks":"5年未満",
      "commodities":"5年未満"
    },
    "relation":{  
      "type":"当社ホームページ",
      "detail":""
    }
  },
  "corporation_info":null
}